// SPDX-License-Identifier: Apache-2.0
// Code authors: Vijay and Codex

// Package bloom checks whether a keyed request or document has probably been
// seen before, using fixed memory. Membership checks can have false positives.
//
// The implementation uses a fixed bitset representation with profile-derived
// bit and hash counts. Hash locations are generated by the deterministic
// sketch-local hash family in spec/hash.md over already-keyed uint64 sketch
// inputs.
package bloom
