// Code authors: Vijay Erramilli and Codex
// Package bloom implements the Go Bloom sketch for llm-sketchkit.
//
// The implementation uses a fixed bitset representation with profile-derived
// bit and hash counts. Hash locations are generated by the deterministic
// sketch-local hash family in spec/hash.md over already-keyed uint64 sketch
// inputs.
package bloom
