# SPDX-License-Identifier: Apache-2.0
# Code authors: Vijay Erramilli and Codex
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: America/New_York
    groups:
      go-minor-and-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: America/New_York
    groups:
      python-minor-and-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: America/New_York
    groups:
      actions-minor-and-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
