// SPDX-License-Identifier: Apache-2.0
// Code authors: Vijay Erramilli and Codex

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: spec/sketches.proto

package sketchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SketchKind int32

const (
	SketchKind_SKETCH_KIND_UNSPECIFIED    SketchKind = 0
	SketchKind_SKETCH_KIND_HLLPP          SketchKind = 1
	SketchKind_SKETCH_KIND_FREQUENT_ITEMS SketchKind = 2
	SketchKind_SKETCH_KIND_BLOOM          SketchKind = 3
	SketchKind_SKETCH_KIND_MINHASH        SketchKind = 4
)

// Enum value maps for SketchKind.
var (
	SketchKind_name = map[int32]string{
		0: "SKETCH_KIND_UNSPECIFIED",
		1: "SKETCH_KIND_HLLPP",
		2: "SKETCH_KIND_FREQUENT_ITEMS",
		3: "SKETCH_KIND_BLOOM",
		4: "SKETCH_KIND_MINHASH",
	}
	SketchKind_value = map[string]int32{
		"SKETCH_KIND_UNSPECIFIED":    0,
		"SKETCH_KIND_HLLPP":          1,
		"SKETCH_KIND_FREQUENT_ITEMS": 2,
		"SKETCH_KIND_BLOOM":          3,
		"SKETCH_KIND_MINHASH":        4,
	}
)

func (x SketchKind) Enum() *SketchKind {
	p := new(SketchKind)
	*p = x
	return p
}

func (x SketchKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SketchKind) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_sketches_proto_enumTypes[0].Descriptor()
}

func (SketchKind) Type() protoreflect.EnumType {
	return &file_spec_sketches_proto_enumTypes[0]
}

func (x SketchKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SketchKind.Descriptor instead.
func (SketchKind) EnumDescriptor() ([]byte, []int) {
	return file_spec_sketches_proto_rawDescGZIP(), []int{0}
}

type HashAlgorithm int32

const (
	HashAlgorithm_HASH_ALGORITHM_UNSPECIFIED    HashAlgorithm = 0
	HashAlgorithm_HASH_ALGORITHM_HMAC_SHA256_64 HashAlgorithm = 1
	HashAlgorithm_HASH_ALGORITHM_SIPHASH_64     HashAlgorithm = 2
)

// Enum value maps for HashAlgorithm.
var (
	HashAlgorithm_name = map[int32]string{
		0: "HASH_ALGORITHM_UNSPECIFIED",
		1: "HASH_ALGORITHM_HMAC_SHA256_64",
		2: "HASH_ALGORITHM_SIPHASH_64",
	}
	HashAlgorithm_value = map[string]int32{
		"HASH_ALGORITHM_UNSPECIFIED":    0,
		"HASH_ALGORITHM_HMAC_SHA256_64": 1,
		"HASH_ALGORITHM_SIPHASH_64":     2,
	}
)

func (x HashAlgorithm) Enum() *HashAlgorithm {
	p := new(HashAlgorithm)
	*p = x
	return p
}

func (x HashAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_sketches_proto_enumTypes[1].Descriptor()
}

func (HashAlgorithm) Type() protoreflect.EnumType {
	return &file_spec_sketches_proto_enumTypes[1]
}

func (x HashAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HashAlgorithm.Descriptor instead.
func (HashAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_spec_sketches_proto_rawDescGZIP(), []int{1}
}

type RepresentationMode int32

const (
	RepresentationMode_REPRESENTATION_MODE_UNSPECIFIED                RepresentationMode = 0
	RepresentationMode_REPRESENTATION_MODE_HLLPP_SPARSE               RepresentationMode = 1
	RepresentationMode_REPRESENTATION_MODE_HLLPP_DENSE                RepresentationMode = 2
	RepresentationMode_REPRESENTATION_MODE_FREQUENT_ITEMS_BOUNDED_MAP RepresentationMode = 3
	RepresentationMode_REPRESENTATION_MODE_BLOOM_BITSET               RepresentationMode = 4
	RepresentationMode_REPRESENTATION_MODE_MINHASH_SIGNATURE          RepresentationMode = 5
)

// Enum value maps for RepresentationMode.
var (
	RepresentationMode_name = map[int32]string{
		0: "REPRESENTATION_MODE_UNSPECIFIED",
		1: "REPRESENTATION_MODE_HLLPP_SPARSE",
		2: "REPRESENTATION_MODE_HLLPP_DENSE",
		3: "REPRESENTATION_MODE_FREQUENT_ITEMS_BOUNDED_MAP",
		4: "REPRESENTATION_MODE_BLOOM_BITSET",
		5: "REPRESENTATION_MODE_MINHASH_SIGNATURE",
	}
	RepresentationMode_value = map[string]int32{
		"REPRESENTATION_MODE_UNSPECIFIED":                0,
		"REPRESENTATION_MODE_HLLPP_SPARSE":               1,
		"REPRESENTATION_MODE_HLLPP_DENSE":                2,
		"REPRESENTATION_MODE_FREQUENT_ITEMS_BOUNDED_MAP": 3,
		"REPRESENTATION_MODE_BLOOM_BITSET":               4,
		"REPRESENTATION_MODE_MINHASH_SIGNATURE":          5,
	}
)

func (x RepresentationMode) Enum() *RepresentationMode {
	p := new(RepresentationMode)
	*p = x
	return p
}

func (x RepresentationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepresentationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_sketches_proto_enumTypes[2].Descriptor()
}

func (RepresentationMode) Type() protoreflect.EnumType {
	return &file_spec_sketches_proto_enumTypes[2]
}

func (x RepresentationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepresentationMode.Descriptor instead.
func (RepresentationMode) EnumDescriptor() ([]byte, []int) {
	return file_spec_sketches_proto_rawDescGZIP(), []int{2}
}

type SketchMetadata struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Kind                   SketchKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=llm.sketchkit.v1.SketchKind" json:"kind,omitempty"`
	WireVersion            uint32                 `protobuf:"varint,2,opt,name=wire_version,json=wireVersion,proto3" json:"wire_version,omitempty"`
	Profile                string                 `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	HashDomain             string                 `protobuf:"bytes,4,opt,name=hash_domain,json=hashDomain,proto3" json:"hash_domain,omitempty"`
	HashAlgo               HashAlgorithm          `protobuf:"varint,5,opt,name=hash_algo,json=hashAlgo,proto3,enum=llm.sketchkit.v1.HashAlgorithm" json:"hash_algo,omitempty"`
	RepresentationMode     RepresentationMode     `protobuf:"varint,6,opt,name=representation_mode,json=representationMode,proto3,enum=llm.sketchkit.v1.RepresentationMode" json:"representation_mode,omitempty"`
	HllppNormalPrecision   *uint32                `protobuf:"varint,20,opt,name=hllpp_normal_precision,json=hllppNormalPrecision,proto3,oneof" json:"hllpp_normal_precision,omitempty"`
	HllppSparsePrecision   *uint32                `protobuf:"varint,21,opt,name=hllpp_sparse_precision,json=hllppSparsePrecision,proto3,oneof" json:"hllpp_sparse_precision,omitempty"`
	FrequentItemsMapSize   *uint32                `protobuf:"varint,22,opt,name=frequent_items_map_size,json=frequentItemsMapSize,proto3,oneof" json:"frequent_items_map_size,omitempty"`
	BloomBitCount          *uint64                `protobuf:"varint,23,opt,name=bloom_bit_count,json=bloomBitCount,proto3,oneof" json:"bloom_bit_count,omitempty"`
	BloomHashCount         *uint32                `protobuf:"varint,24,opt,name=bloom_hash_count,json=bloomHashCount,proto3,oneof" json:"bloom_hash_count,omitempty"`
	MinhashSignatureLength *uint32                `protobuf:"varint,25,opt,name=minhash_signature_length,json=minhashSignatureLength,proto3,oneof" json:"minhash_signature_length,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SketchMetadata) Reset() {
	*x = SketchMetadata{}
	mi := &file_spec_sketches_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SketchMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchMetadata) ProtoMessage() {}

func (x *SketchMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_spec_sketches_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchMetadata.ProtoReflect.Descriptor instead.
func (*SketchMetadata) Descriptor() ([]byte, []int) {
	return file_spec_sketches_proto_rawDescGZIP(), []int{0}
}

func (x *SketchMetadata) GetKind() SketchKind {
	if x != nil {
		return x.Kind
	}
	return SketchKind_SKETCH_KIND_UNSPECIFIED
}

func (x *SketchMetadata) GetWireVersion() uint32 {
	if x != nil {
		return x.WireVersion
	}
	return 0
}

func (x *SketchMetadata) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *SketchMetadata) GetHashDomain() string {
	if x != nil {
		return x.HashDomain
	}
	return ""
}

func (x *SketchMetadata) GetHashAlgo() HashAlgorithm {
	if x != nil {
		return x.HashAlgo
	}
	return HashAlgorithm_HASH_ALGORITHM_UNSPECIFIED
}

func (x *SketchMetadata) GetRepresentationMode() RepresentationMode {
	if x != nil {
		return x.RepresentationMode
	}
	return RepresentationMode_REPRESENTATION_MODE_UNSPECIFIED
}

func (x *SketchMetadata) GetHllppNormalPrecision() uint32 {
	if x != nil && x.HllppNormalPrecision != nil {
		return *x.HllppNormalPrecision
	}
	return 0
}

func (x *SketchMetadata) GetHllppSparsePrecision() uint32 {
	if x != nil && x.HllppSparsePrecision != nil {
		return *x.HllppSparsePrecision
	}
	return 0
}

func (x *SketchMetadata) GetFrequentItemsMapSize() uint32 {
	if x != nil && x.FrequentItemsMapSize != nil {
		return *x.FrequentItemsMapSize
	}
	return 0
}

func (x *SketchMetadata) GetBloomBitCount() uint64 {
	if x != nil && x.BloomBitCount != nil {
		return *x.BloomBitCount
	}
	return 0
}

func (x *SketchMetadata) GetBloomHashCount() uint32 {
	if x != nil && x.BloomHashCount != nil {
		return *x.BloomHashCount
	}
	return 0
}

func (x *SketchMetadata) GetMinhashSignatureLength() uint32 {
	if x != nil && x.MinhashSignatureLength != nil {
		return *x.MinhashSignatureLength
	}
	return 0
}

type Sketch struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *SketchMetadata        `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Sketch_Hllpp
	//	*Sketch_FrequentItems
	//	*Sketch_Bloom
	//	*Sketch_Minhash
	Body          isSketch_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sketch) Reset() {
	*x = Sketch{}
	mi := &file_spec_sketches_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sketch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sketch) ProtoMessage() {}

func (x *Sketch) ProtoReflect() protoreflect.Message {
	mi := &file_spec_sketches_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sketch.ProtoReflect.Descriptor instead.
func (*Sketch) Descriptor() ([]byte, []int) {
	return file_spec_sketches_proto_rawDescGZIP(), []int{1}
}

func (x *Sketch) GetMetadata() *SketchMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Sketch) GetBody() isSketch_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Sketch) GetHllpp() *HllppSketch {
	if x != nil {
		if x, ok := x.Body.(*Sketch_Hllpp); ok {
			return x.Hllpp
		}
	}
	return nil
}

func (x *Sketch) GetFrequentItems() *FrequentItemsSketch {
	if x != nil {
		if x, ok := x.Body.(*Sketch_FrequentItems); ok {
			return x.FrequentItems
		}
	}
	return nil
}

func (x *Sketch) GetBloom() *BloomSketch {
	if x != nil {
		if x, ok := x.Body.(*Sketch_Bloom); ok {
			return x.Bloom
		}
	}
	return nil
}

func (x *Sketch) GetMinhash() *MinHashSketch {
	if x != nil {
		if x, ok := x.Body.(*Sketch_Minhash); ok {
			return x.Minhash
		}
	}
	return nil
}

type isSketch_Body interface {
	isSketch_Body()
}

type Sketch_Hllpp struct {
	Hllpp *HllppSketch `protobuf:"bytes,10,opt,name=hllpp,proto3,oneof"`
}

type Sketch_FrequentItems struct {
	FrequentItems *FrequentItemsSketch `protobuf:"bytes,11,opt,name=frequent_items,json=frequentItems,proto3,oneof"`
}

type Sketch_Bloom struct {
	Bloom *BloomSketch `protobuf:"bytes,12,opt,name=bloom,proto3,oneof"`
}

type Sketch_Minhash struct {
	Minhash *MinHashSketch `protobuf:"bytes,13,opt,name=minhash,proto3,oneof"`
}

func (*Sketch_Hllpp) isSketch_Body() {}

func (*Sketch_FrequentItems) isSketch_Body() {}

func (*Sketch_Bloom) isSketch_Body() {}

func (*Sketch_Minhash) isSketch_Body() {}

type HllppSketch struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SparseRegisters []*HllppSparseRegister `protobuf:"bytes,1,rep,name=sparse_registers,json=sparseRegisters,proto3" json:"sparse_registers,omitempty"`
	DenseRegisters  []byte                 `protobuf:"bytes,2,opt,name=dense_registers,json=denseRegisters,proto3" json:"dense_registers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HllppSketch) Reset() {
	*x = HllppSketch{}
	mi := &file_spec_sketches_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HllppSketch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HllppSketch) ProtoMessage() {}

func (x *HllppSketch) ProtoReflect() protoreflect.Message {
	mi := &file_spec_sketches_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HllppSketch.ProtoReflect.Descriptor instead.
func (*HllppSketch) Descriptor() ([]byte, []int) {
	return file_spec_sketches_proto_rawDescGZIP(), []int{2}
}

func (x *HllppSketch) GetSparseRegisters() []*HllppSparseRegister {
	if x != nil {
		return x.SparseRegisters
	}
	return nil
}

func (x *HllppSketch) GetDenseRegisters() []byte {
	if x != nil {
		return x.DenseRegisters
	}
	return nil
}

type HllppSparseRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value         uint32                 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HllppSparseRegister) Reset() {
	*x = HllppSparseRegister{}
	mi := &file_spec_sketches_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HllppSparseRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HllppSparseRegister) ProtoMessage() {}

func (x *HllppSparseRegister) ProtoReflect() protoreflect.Message {
	mi := &file_spec_sketches_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HllppSparseRegister.ProtoReflect.Descriptor instead.
func (*HllppSparseRegister) Descriptor() ([]byte, []int) {
	return file_spec_sketches_proto_rawDescGZIP(), []int{3}
}

func (x *HllppSparseRegister) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *HllppSparseRegister) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type FrequentItemsSketch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FrequentItemsEntry  `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	TotalWeight   int64                  `protobuf:"varint,2,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	MaxError      int64                  `protobuf:"varint,3,opt,name=max_error,json=maxError,proto3" json:"max_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrequentItemsSketch) Reset() {
	*x = FrequentItemsSketch{}
	mi := &file_spec_sketches_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrequentItemsSketch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrequentItemsSketch) ProtoMessage() {}

func (x *FrequentItemsSketch) ProtoReflect() protoreflect.Message {
	mi := &file_spec_sketches_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrequentItemsSketch.ProtoReflect.Descriptor instead.
func (*FrequentItemsSketch) Descriptor() ([]byte, []int) {
	return file_spec_sketches_proto_rawDescGZIP(), []int{4}
}

func (x *FrequentItemsSketch) GetEntries() []*FrequentItemsEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *FrequentItemsSketch) GetTotalWeight() int64 {
	if x != nil {
		return x.TotalWeight
	}
	return 0
}

func (x *FrequentItemsSketch) GetMaxError() int64 {
	if x != nil {
		return x.MaxError
	}
	return 0
}

type FrequentItemsEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          uint64                 `protobuf:"fixed64,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Estimate      int64                  `protobuf:"varint,2,opt,name=estimate,proto3" json:"estimate,omitempty"`
	Error         int64                  `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrequentItemsEntry) Reset() {
	*x = FrequentItemsEntry{}
	mi := &file_spec_sketches_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrequentItemsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrequentItemsEntry) ProtoMessage() {}

func (x *FrequentItemsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_spec_sketches_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrequentItemsEntry.ProtoReflect.Descriptor instead.
func (*FrequentItemsEntry) Descriptor() ([]byte, []int) {
	return file_spec_sketches_proto_rawDescGZIP(), []int{5}
}

func (x *FrequentItemsEntry) GetHash() uint64 {
	if x != nil {
		return x.Hash
	}
	return 0
}

func (x *FrequentItemsEntry) GetEstimate() int64 {
	if x != nil {
		return x.Estimate
	}
	return 0
}

func (x *FrequentItemsEntry) GetError() int64 {
	if x != nil {
		return x.Error
	}
	return 0
}

type BloomSketch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bitset        []byte                 `protobuf:"bytes,1,opt,name=bitset,proto3" json:"bitset,omitempty"`
	InsertedCount uint64                 `protobuf:"varint,2,opt,name=inserted_count,json=insertedCount,proto3" json:"inserted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BloomSketch) Reset() {
	*x = BloomSketch{}
	mi := &file_spec_sketches_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BloomSketch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloomSketch) ProtoMessage() {}

func (x *BloomSketch) ProtoReflect() protoreflect.Message {
	mi := &file_spec_sketches_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloomSketch.ProtoReflect.Descriptor instead.
func (*BloomSketch) Descriptor() ([]byte, []int) {
	return file_spec_sketches_proto_rawDescGZIP(), []int{6}
}

func (x *BloomSketch) GetBitset() []byte {
	if x != nil {
		return x.Bitset
	}
	return nil
}

func (x *BloomSketch) GetInsertedCount() uint64 {
	if x != nil {
		return x.InsertedCount
	}
	return 0
}

type MinHashSketch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Signature      []uint64               `protobuf:"fixed64,1,rep,packed,name=signature,proto3" json:"signature,omitempty"`
	PopulatedCount uint64                 `protobuf:"varint,2,opt,name=populated_count,json=populatedCount,proto3" json:"populated_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MinHashSketch) Reset() {
	*x = MinHashSketch{}
	mi := &file_spec_sketches_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinHashSketch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinHashSketch) ProtoMessage() {}

func (x *MinHashSketch) ProtoReflect() protoreflect.Message {
	mi := &file_spec_sketches_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinHashSketch.ProtoReflect.Descriptor instead.
func (*MinHashSketch) Descriptor() ([]byte, []int) {
	return file_spec_sketches_proto_rawDescGZIP(), []int{7}
}

func (x *MinHashSketch) GetSignature() []uint64 {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *MinHashSketch) GetPopulatedCount() uint64 {
	if x != nil {
		return x.PopulatedCount
	}
	return 0
}

var File_spec_sketches_proto protoreflect.FileDescriptor

const file_spec_sketches_proto_rawDesc = "" +
	"\n" +
	"\x13spec/sketches.proto\x12\x10llm.sketchkit.v1\"\x9a\x06\n" +
	"\x0eSketchMetadata\x120\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1c.llm.sketchkit.v1.SketchKindR\x04kind\x12!\n" +
	"\fwire_version\x18\x02 \x01(\rR\vwireVersion\x12\x18\n" +
	"\aprofile\x18\x03 \x01(\tR\aprofile\x12\x1f\n" +
	"\vhash_domain\x18\x04 \x01(\tR\n" +
	"hashDomain\x12<\n" +
	"\thash_algo\x18\x05 \x01(\x0e2\x1f.llm.sketchkit.v1.HashAlgorithmR\bhashAlgo\x12U\n" +
	"\x13representation_mode\x18\x06 \x01(\x0e2$.llm.sketchkit.v1.RepresentationModeR\x12representationMode\x129\n" +
	"\x16hllpp_normal_precision\x18\x14 \x01(\rH\x00R\x14hllppNormalPrecision\x88\x01\x01\x129\n" +
	"\x16hllpp_sparse_precision\x18\x15 \x01(\rH\x01R\x14hllppSparsePrecision\x88\x01\x01\x12:\n" +
	"\x17frequent_items_map_size\x18\x16 \x01(\rH\x02R\x14frequentItemsMapSize\x88\x01\x01\x12+\n" +
	"\x0fbloom_bit_count\x18\x17 \x01(\x04H\x03R\rbloomBitCount\x88\x01\x01\x12-\n" +
	"\x10bloom_hash_count\x18\x18 \x01(\rH\x04R\x0ebloomHashCount\x88\x01\x01\x12=\n" +
	"\x18minhash_signature_length\x18\x19 \x01(\rH\x05R\x16minhashSignatureLength\x88\x01\x01B\x19\n" +
	"\x17_hllpp_normal_precisionB\x19\n" +
	"\x17_hllpp_sparse_precisionB\x1a\n" +
	"\x18_frequent_items_map_sizeB\x12\n" +
	"\x10_bloom_bit_countB\x13\n" +
	"\x11_bloom_hash_countB\x1b\n" +
	"\x19_minhash_signature_length\"\xc9\x02\n" +
	"\x06Sketch\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2 .llm.sketchkit.v1.SketchMetadataR\bmetadata\x125\n" +
	"\x05hllpp\x18\n" +
	" \x01(\v2\x1d.llm.sketchkit.v1.HllppSketchH\x00R\x05hllpp\x12N\n" +
	"\x0efrequent_items\x18\v \x01(\v2%.llm.sketchkit.v1.FrequentItemsSketchH\x00R\rfrequentItems\x125\n" +
	"\x05bloom\x18\f \x01(\v2\x1d.llm.sketchkit.v1.BloomSketchH\x00R\x05bloom\x12;\n" +
	"\aminhash\x18\r \x01(\v2\x1f.llm.sketchkit.v1.MinHashSketchH\x00R\aminhashB\x06\n" +
	"\x04body\"\x88\x01\n" +
	"\vHllppSketch\x12P\n" +
	"\x10sparse_registers\x18\x01 \x03(\v2%.llm.sketchkit.v1.HllppSparseRegisterR\x0fsparseRegisters\x12'\n" +
	"\x0fdense_registers\x18\x02 \x01(\fR\x0edenseRegisters\"A\n" +
	"\x13HllppSparseRegister\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value\"\x95\x01\n" +
	"\x13FrequentItemsSketch\x12>\n" +
	"\aentries\x18\x01 \x03(\v2$.llm.sketchkit.v1.FrequentItemsEntryR\aentries\x12!\n" +
	"\ftotal_weight\x18\x02 \x01(\x03R\vtotalWeight\x12\x1b\n" +
	"\tmax_error\x18\x03 \x01(\x03R\bmaxError\"Z\n" +
	"\x12FrequentItemsEntry\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\x06R\x04hash\x12\x1a\n" +
	"\bestimate\x18\x02 \x01(\x03R\bestimate\x12\x14\n" +
	"\x05error\x18\x03 \x01(\x03R\x05error\"L\n" +
	"\vBloomSketch\x12\x16\n" +
	"\x06bitset\x18\x01 \x01(\fR\x06bitset\x12%\n" +
	"\x0einserted_count\x18\x02 \x01(\x04R\rinsertedCount\"V\n" +
	"\rMinHashSketch\x12\x1c\n" +
	"\tsignature\x18\x01 \x03(\x06R\tsignature\x12'\n" +
	"\x0fpopulated_count\x18\x02 \x01(\x04R\x0epopulatedCount*\x90\x01\n" +
	"\n" +
	"SketchKind\x12\x1b\n" +
	"\x17SKETCH_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SKETCH_KIND_HLLPP\x10\x01\x12\x1e\n" +
	"\x1aSKETCH_KIND_FREQUENT_ITEMS\x10\x02\x12\x15\n" +
	"\x11SKETCH_KIND_BLOOM\x10\x03\x12\x17\n" +
	"\x13SKETCH_KIND_MINHASH\x10\x04*q\n" +
	"\rHashAlgorithm\x12\x1e\n" +
	"\x1aHASH_ALGORITHM_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dHASH_ALGORITHM_HMAC_SHA256_64\x10\x01\x12\x1d\n" +
	"\x19HASH_ALGORITHM_SIPHASH_64\x10\x02*\x89\x02\n" +
	"\x12RepresentationMode\x12#\n" +
	"\x1fREPRESENTATION_MODE_UNSPECIFIED\x10\x00\x12$\n" +
	" REPRESENTATION_MODE_HLLPP_SPARSE\x10\x01\x12#\n" +
	"\x1fREPRESENTATION_MODE_HLLPP_DENSE\x10\x02\x122\n" +
	".REPRESENTATION_MODE_FREQUENT_ITEMS_BOUNDED_MAP\x10\x03\x12$\n" +
	" REPRESENTATION_MODE_BLOOM_BITSET\x10\x04\x12)\n" +
	"%REPRESENTATION_MODE_MINHASH_SIGNATURE\x10\x05BLZJgithub.com/llm-measurement/llm-sketchkit/go/sketchkit/internal/pb;sketchpbb\x06proto3"

var (
	file_spec_sketches_proto_rawDescOnce sync.Once
	file_spec_sketches_proto_rawDescData []byte
)

func file_spec_sketches_proto_rawDescGZIP() []byte {
	file_spec_sketches_proto_rawDescOnce.Do(func() {
		file_spec_sketches_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spec_sketches_proto_rawDesc), len(file_spec_sketches_proto_rawDesc)))
	})
	return file_spec_sketches_proto_rawDescData
}

var file_spec_sketches_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_spec_sketches_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_spec_sketches_proto_goTypes = []any{
	(SketchKind)(0),             // 0: llm.sketchkit.v1.SketchKind
	(HashAlgorithm)(0),          // 1: llm.sketchkit.v1.HashAlgorithm
	(RepresentationMode)(0),     // 2: llm.sketchkit.v1.RepresentationMode
	(*SketchMetadata)(nil),      // 3: llm.sketchkit.v1.SketchMetadata
	(*Sketch)(nil),              // 4: llm.sketchkit.v1.Sketch
	(*HllppSketch)(nil),         // 5: llm.sketchkit.v1.HllppSketch
	(*HllppSparseRegister)(nil), // 6: llm.sketchkit.v1.HllppSparseRegister
	(*FrequentItemsSketch)(nil), // 7: llm.sketchkit.v1.FrequentItemsSketch
	(*FrequentItemsEntry)(nil),  // 8: llm.sketchkit.v1.FrequentItemsEntry
	(*BloomSketch)(nil),         // 9: llm.sketchkit.v1.BloomSketch
	(*MinHashSketch)(nil),       // 10: llm.sketchkit.v1.MinHashSketch
}
var file_spec_sketches_proto_depIdxs = []int32{
	0,  // 0: llm.sketchkit.v1.SketchMetadata.kind:type_name -> llm.sketchkit.v1.SketchKind
	1,  // 1: llm.sketchkit.v1.SketchMetadata.hash_algo:type_name -> llm.sketchkit.v1.HashAlgorithm
	2,  // 2: llm.sketchkit.v1.SketchMetadata.representation_mode:type_name -> llm.sketchkit.v1.RepresentationMode
	3,  // 3: llm.sketchkit.v1.Sketch.metadata:type_name -> llm.sketchkit.v1.SketchMetadata
	5,  // 4: llm.sketchkit.v1.Sketch.hllpp:type_name -> llm.sketchkit.v1.HllppSketch
	7,  // 5: llm.sketchkit.v1.Sketch.frequent_items:type_name -> llm.sketchkit.v1.FrequentItemsSketch
	9,  // 6: llm.sketchkit.v1.Sketch.bloom:type_name -> llm.sketchkit.v1.BloomSketch
	10, // 7: llm.sketchkit.v1.Sketch.minhash:type_name -> llm.sketchkit.v1.MinHashSketch
	6,  // 8: llm.sketchkit.v1.HllppSketch.sparse_registers:type_name -> llm.sketchkit.v1.HllppSparseRegister
	8,  // 9: llm.sketchkit.v1.FrequentItemsSketch.entries:type_name -> llm.sketchkit.v1.FrequentItemsEntry
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_spec_sketches_proto_init() }
func file_spec_sketches_proto_init() {
	if File_spec_sketches_proto != nil {
		return
	}
	file_spec_sketches_proto_msgTypes[0].OneofWrappers = []any{}
	file_spec_sketches_proto_msgTypes[1].OneofWrappers = []any{
		(*Sketch_Hllpp)(nil),
		(*Sketch_FrequentItems)(nil),
		(*Sketch_Bloom)(nil),
		(*Sketch_Minhash)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spec_sketches_proto_rawDesc), len(file_spec_sketches_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spec_sketches_proto_goTypes,
		DependencyIndexes: file_spec_sketches_proto_depIdxs,
		EnumInfos:         file_spec_sketches_proto_enumTypes,
		MessageInfos:      file_spec_sketches_proto_msgTypes,
	}.Build()
	File_spec_sketches_proto = out.File
	file_spec_sketches_proto_goTypes = nil
	file_spec_sketches_proto_depIdxs = nil
}
